version: "3.8"

services:
  lambda-fastapi-prod:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: 820426543822.dkr.ecr.ap-northeast-2.amazonaws.com/lambda-fastapi:latest
    container_name: lambda-fastapi-prod
    ports:
      - 9000:8080

  lambda-fastapi-dev:
    build:
      context: . # context는 docker build 명령을 실행할 디렉토리 경로
      dockerfile: ./compose/dev/Dockerfile # 도커파일 지정
    image: lambda-fastapi-dev:latest # 태그 또는 image ID를 지정한다.
    container_name: lambda-fastapi-dev # 컨테이너 이름
    volumes:
      # volume: 컨테이너를 휘발되지 않도록 저장하는 저장공간
      # volumes는 패스와 볼륨을 마운트한다.
      # <호스트>:<컨테이너> -> 현재 app 폴더를 컨테이너의 /usr/src/app 폴더에 마운트시킨다.
      - ./app:/usr/src/app
    ports: # 포트지정 <호스트 포트>:<컨테이너 포트> 또는 <컨테이너 포트>만 지정
      - 8000:8000